//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMEntities : DbContext
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_ChangeSoftware> Tbl_ChangeSoftware { get; set; }
        public virtual DbSet<Tbl_Customer> Tbl_Customer { get; set; }
        public virtual DbSet<Tbl_Customer_Products> Tbl_Customer_Products { get; set; }
        public virtual DbSet<Tbl_CustomerField> Tbl_CustomerField { get; set; }
        public virtual DbSet<Tbl_DeviceFailure> Tbl_DeviceFailure { get; set; }
        public virtual DbSet<Tbl_GetDevice> Tbl_GetDevice { get; set; }
        public virtual DbSet<Tbl_Group> Tbl_Group { get; set; }
        public virtual DbSet<Tbl_Group_Activity> Tbl_Group_Activity { get; set; }
        public virtual DbSet<Tbl_Hardware> Tbl_Hardware { get; set; }
        public virtual DbSet<Tbl_HardwareType> Tbl_HardwareType { get; set; }
        public virtual DbSet<Tbl_Installation> Tbl_Installation { get; set; }
        public virtual DbSet<Tbl_Log> Tbl_Log { get; set; }
        public virtual DbSet<Tbl_MainActivity> Tbl_MainActivity { get; set; }
        public virtual DbSet<Tbl_OtherRequest> Tbl_OtherRequest { get; set; }
        public virtual DbSet<Tbl_Payment> Tbl_Payment { get; set; }
        public virtual DbSet<Tbl_PreInvoice> Tbl_PreInvoice { get; set; }
        public virtual DbSet<Tbl_PreInvoiceType> Tbl_PreInvoiceType { get; set; }
        public virtual DbSet<Tbl_Products> Tbl_Products { get; set; }
        public virtual DbSet<Tbl_RequestType> Tbl_RequestType { get; set; }
        public virtual DbSet<Tbl_ReturnRepairedDevice> Tbl_ReturnRepairedDevice { get; set; }
        public virtual DbSet<Tbl_Section> Tbl_Section { get; set; }
        public virtual DbSet<Tbl_SendToRepair> Tbl_SendToRepair { get; set; }
        public virtual DbSet<Tbl_Software> Tbl_Software { get; set; }
        public virtual DbSet<Tbl_SoftwareType> Tbl_SoftwareType { get; set; }
        public virtual DbSet<Tbl_SubActivity> Tbl_SubActivity { get; set; }
        public virtual DbSet<Tbl_SupportServices> Tbl_SupportServices { get; set; }
        public virtual DbSet<Tbl_Training> Tbl_Training { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_User_Group> Tbl_User_Group { get; set; }
    }
}
