//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Payment
    {
        public int Payment_ID { get; set; }
        public int Customer_ID { get; set; }
        public string PreInvoiceNumber { get; set; }
        public string PaymentDate { get; set; }
        public int PaymentAmount { get; set; }
        public string Description { get; set; }
        public int LastUpdateUser_ID { get; set; }
        public string LastUpdateDate { get; set; }
        public string LastUpdateTime { get; set; }
    
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
