//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Group_Activity
    {
        public int GrpAct_ID { get; set; }
        public int Group_ID { get; set; }
        public int SubAct_ID { get; set; }
        public int Active { get; set; }
        public int LastUpdateUser_ID { get; set; }
        public string LastUpdateDate { get; set; }
        public string LastUpdateTime { get; set; }
    
        public virtual Tbl_Group Tbl_Group { get; set; }
        public virtual Tbl_SubActivity Tbl_SubActivity { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
