//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SubActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SubActivity()
        {
            this.Tbl_Group_Activity = new HashSet<Tbl_Group_Activity>();
        }
    
        public int SubAct_ID { get; set; }
        public int MainAct_ID { get; set; }
        public string SubActName { get; set; }
        public int Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Group_Activity> Tbl_Group_Activity { get; set; }
        public virtual Tbl_MainActivity Tbl_MainActivity { get; set; }
    }
}
