//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PreInvoice
    {
        public int PreInvoice_ID { get; set; }
        public int PreInvoiceType_ID { get; set; }
        public string PreInvoiceNumber { get; set; }
        public string IssueDate { get; set; }
        public int SendingStatus { get; set; }
        public byte[] PreInvoiceUpload { get; set; }
        public string Description { get; set; }
        public int LastUpdateUser_ID { get; set; }
        public string LastUpdateDate { get; set; }
        public string LastUpdateTime { get; set; }
        public Nullable<int> ConfirmationStatus { get; set; }
        public int Customer_ID { get; set; }
    
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        public virtual Tbl_PreInvoiceType Tbl_PreInvoiceType { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
