//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Installation
    {
        public int Installation_ID { get; set; }
        public int Customer_ID { get; set; }
        public string CustomerConnector { get; set; }
        public int SendSystemRequirements { get; set; }
        public int InstallationLocation { get; set; }
        public int InstallationProgram { get; set; }
        public string DeliveryDate_SOHA { get; set; }
        public string DeliveryDate_Customer { get; set; }
        public int ClientsNumber { get; set; }
        public string PurchasedDevicesNumber { get; set; }
        public string AdministratorPassword { get; set; }
        public string IPServer { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public int SystemType { get; set; }
        public string Description { get; set; }
        public int LastUpdateUser_ID { get; set; }
        public string LastUpdateDate { get; set; }
        public string LastUpdateTime { get; set; }
    
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
