//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HardwareType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_HardwareType()
        {
            this.Tbl_Hardware = new HashSet<Tbl_Hardware>();
        }
    
        public int Hardware_ID { get; set; }
        public string HardwareName { get; set; }
        public int Products_ID { get; set; }
        public int HardwarePrice { get; set; }
        public string WarrantyPeriod { get; set; }
        public string Description { get; set; }
        public int LastUpdateUser_ID { get; set; }
        public string LastUpdateDate { get; set; }
        public string LastUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hardware> Tbl_Hardware { get; set; }
        public virtual Tbl_Products Tbl_Products { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
