//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hardware
    {
        public int Request_ID { get; set; }
        public int Customer_ID { get; set; }
        public string CustomerConnector { get; set; }
        public int Hardware_ID { get; set; }
        public string RequestDate { get; set; }
        public int Amount { get; set; }
        public int Status { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveryDeviceSerialNumber { get; set; }
        public string DeliveryDescription { get; set; }
        public string Description { get; set; }
        public int LastUpdateUser_ID { get; set; }
        public string LastUpdateDate { get; set; }
        public string LastUpdateTime { get; set; }
    
        public virtual Tbl_Customer Tbl_Customer { get; set; }
        public virtual Tbl_HardwareType Tbl_HardwareType { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
